# Generated by Django 2.0 on 2017-12-20 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dodany', 'Dodany'), ('realizowany', 'Realizowany'), ('zakończony', 'Zakończony')], default='Dodany', max_length=20)),
                ('data_dodania', models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 22, 17, 924901, tzinfo=utc))),
                ('uaktualniony', models.DateTimeField(auto_now=True)),
                ('lp', models.IntegerField()),
                ('sufix', models.CharField(blank=True, max_length=30)),
                ('inwestor', models.CharField(blank=True, max_length=30)),
                ('nr_umowy', models.CharField(blank=True, max_length=30)),
                ('kod', models.CharField(blank=True, max_length=30)),
                ('kierownik', models.CharField(blank=True, max_length=30)),
                ('fv', models.CharField(blank=True, max_length=200)),
                ('projekt', models.CharField(blank=True, max_length=200)),
                ('data_roznicowki', models.DateField(blank=True, null=True)),
                ('data_realizacji', models.DateField(blank=True, null=True)),
                ('wykonawca', models.CharField(blank=True, max_length=30)),
                ('uwagi', models.TextField(blank=True)),
                ('kraj', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baza_rekord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_dodania',),
            },
        ),
    ]
