# Generated by Django 2.0 on 2017-12-20 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 20, 19, 24, 2, 778009, tzinfo=utc)),
        ),
    ]
