# Generated by Django 2.0 on 2017-12-20 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0002_auto_20171220_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data_dodania',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
