# Generated by Django 2.0 on 2017-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0003_auto_20171220_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='data_dodania',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
