# Generated by Django 2.0 on 2017-12-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('dodany', 'Dodany'), ('realizowany', 'Realizowany'), ('zakończony', 'Zakończony')], default='Dodany', max_length=20),
        ),
    ]
