# Generated by Django 2.0 on 2017-12-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vide',
            new_name='Video',
        ),
    ]
