# Generated by Django 2.0 on 2017-12-22 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0003_auto_20171221_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ('-entry_date',)},
        ),
        migrations.AlterField(
            model_name='row',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 10, 14, 1, 416098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='row',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
