# Generated by Django 2.0 on 2018-02-20 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0004_auto_20171222_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='afd',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='row',
            name='customer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='row',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='row',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
