# Generated by Django 2.0 on 2017-12-21 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='enter_code',
            new_name='entry_code',
        ),
        migrations.AlterField(
            model_name='row',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 16, 55, 43, 885124, tzinfo=utc)),
        ),
    ]
