# Generated by Django 2.0 on 2017-12-21 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kartoteka', '0002_auto_20171221_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='row',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 16, 58, 42, 653873, tzinfo=utc)),
        ),
    ]
